spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ivms
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      port: 27017
      host: localhost
      database: uploads

server:
  port: 8080

app:
  jwtSecret: 
  jwtExpirationMs: 86400000
